Project/Areas/Adimen/Controllers/CataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nest;
using Project_Data_Access.Repository;
using Project_Model;
using Project_Model.VIewModel;
using Project_utility;

namespace Project.Areas.Adimen.Controllers
{
    [Area("Adimen")]
   // [Authorize(Roles =SD.Role_Admin)]
    public class CataController : Controller
    {
        private readonly Iunitofwork _unitofwork;
        public CataController(Iunitofwork unitofwork)
        {
            _unitofwork = unitofwork;
        }
       
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult pageing(int CurrentPage = 1,string term="",string orderby="")
        {
            
            int pageSize = 5;

            // Initialize the ViewModel
            CategoryVM categoryVM = new CategoryVM()
            {
                Catagory = new catagory(),
                CatagoriesList = _unitofwork.catagory.Getall()
                                    .Select(c => new SelectListItem
                                    {
                                        Text = c.Name,
                                        Value = c.Id.ToString()
                                    })
                                    .Skip((CurrentPage - 1) * pageSize)
                                    .Take(pageSize)
                                    .ToList()
            };

            // Count the total number of categories
            int totalRecords = _unitofwork.catagory.Getall().Count();
            int totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            // Pass the ViewModel, the total count, total pages, and current page to the view
           categoryVM.CurrentPage = CurrentPage;
            categoryVM.TotalPage= totalPages;
            categoryVM.Term= term;
            categoryVM.Orderby= orderby;
            categoryVM.PageSize = pageSize;


            return View(categoryVM);
        }



        public IActionResult upsert(int? id)

        {
            catagory catagory = new catagory();
            if(id==null)return View(catagory);//Creat Code
            //Edit
            catagory=_unitofwork.catagory.get(id.GetValueOrDefault());
            if (catagory == null) return NotFound();
            return View(catagory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult upsert(catagory catagory)
        {
            if(catagory == null) return NotFound(); 
            if(!ModelState.IsValid) return View(catagory);
            if (catagory.Id==0)
                _unitofwork.catagory.Add(catagory);
            else
                _unitofwork.catagory.update(catagory);
            _unitofwork.save();
            return RedirectToAction("Index");

        }
        
       
        #region APIs
        [HttpGet]
        public IActionResult GetAll(int? id)
        {
            var categoryList = _unitofwork.catagory.Getall();
            return Json(new { data = categoryList });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var cat = _unitofwork.catagory.get(id);
            if (cat == null) return Json(new
            {success = false,message = "Something went !!!"
            });
            _unitofwork.catagory.Remove(cat);
            _unitofwork.save();
            return Json(new { success=true, message="Data is Delete suceess!!!" });
        }
         
        #endregion

    }
}

Project/Areas/Adimen/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Project_Data_Access.Repository;
using Project_Model;
using Project_utility;

namespace Project.Areas.Adimen.Controllers
{
    [Area("Adimen")]
   // [Authorize(Roles =SD.Role_Admin +","+SD.Role_Employee)]
    public class CompanyController : Controller
    {
        private readonly Iunitofwork _unitofwork;
        public CompanyController(Iunitofwork unitofwork)
        {
               _unitofwork= unitofwork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult upsert(int? id)
        {
            Company company = new Company();
            if (id == null) return View(company);
            company=_unitofwork.Company.get(id.GetValueOrDefault());
            if (company == null) return NotFound();


            return View(company);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult upsert(Company company)
        {
            if (company == null) return NotFound();
            if (!ModelState.IsValid) return View(company);
            if (company.Id == 0)
                _unitofwork.Company.Add(company);
            else
                _unitofwork.Company.update(company);
            _unitofwork.save();
            return RedirectToAction("Index");
        }
            #region APIs
            [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data=_unitofwork.Company.Getall() }); 
        }
        #endregion
    }
}

Project/Areas/Adimen/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Project_Data_Access.Repository;
using Project_Model;
using Project_Model.VIewModel;
using Project_utility;
using System.Data;

namespace Project.Areas.Adimen.Controllers
{
    [Area("Adimen")]
   // [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly Iunitofwork _unitofwork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(Iunitofwork unitowork, IWebHostEnvironment webHostEnvironment)
        {
            _unitofwork = unitowork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),

                catalist = _unitofwork.catagory.Getall().Select(cl => new SelectListItem()
                {
                    Text = cl.Name,
           
                    
                    Value = cl.Id.ToString()
                }),
                covertypeList = _unitofwork.Covertype.Getall().Select(ct => new SelectListItem()
                {
                    Text = ct.Name,
                    Value = ct.Id.ToString()
                }
             ),
              
            };
            if (id == null) return View(productVM);
            productVM.Product = _unitofwork.Product.get(id.GetValueOrDefault());
            return View(productVM);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult upsert(ProductVM productVM)
        {   
            if (!ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (files.Count() > 0)
                {
                    var filename = Guid.NewGuid().ToString();

                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(webRootPath, @"Images\Products");
                    if (productVM.Product.Id != 0)
                    {
                        var ImagerExists = _unitofwork.Product.get(productVM.Product.Id).ImgeUrl;
                        productVM.Product.ImgeUrl = ImagerExists;
                    }
                    if (productVM.Product.ImgeUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, productVM.Product.ImgeUrl.Trim('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var filestream = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    productVM.Product.ImgeUrl = @"\Images\Products\" + filename + extension;
                }
                else
                {
                    if (productVM.Product.Id != 0)
                    {
                        var imageexists = _unitofwork.Product.get(productVM.Product.Id).ImgeUrl;
                        productVM.Product.ImgeUrl = imageexists;
                    }
                }
                if (productVM.Product.Id == 0)
                   

                    _unitofwork.Product.Add(productVM.Product);
                else
                    _unitofwork.Product.update(productVM.Product);
                _unitofwork.save();
                return RedirectToAction("Index");

            }   
            else
            {
                productVM = new ProductVM()
                {
                    Product = new Product(),

                    catalist = _unitofwork.catagory.Getall().Select(cl => new SelectListItem()
                    {
                        Text = cl.Name,
                        Value = cl.Id.ToString()
                    }),
                    covertypeList = _unitofwork.Covertype.Getall().Select(ct => new SelectListItem()
                    {
                        Text = ct.Name,
                        Value = ct.Id.ToString()
                    }
             )
                };
                if (productVM.Product.Id != 0)
                {
                    productVM.Product = _unitofwork.Product.get(productVM.Product.Id);
                }
                return View(productVM);

            }

        
    }
    #region APIs
    [HttpGet]
    public IActionResult getall()
    {
        var productlist = _unitofwork.Product.Getall();
            return Json(new { data = productlist });
    }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var cat = _unitofwork.Product.get(id);
            if (cat == null) return Json(new
            {
                success = false,
                message = "Something went !!!"
            });
            var wabRootPath = _webHostEnvironment.WebRootPath;
            var imgePath = Path.Combine(wabRootPath, cat.ImgeUrl.Trim('\\'));
            if(System.IO.File.Exists(imgePath))
            {
                System.IO.File.Exists(imgePath);
            }
            _unitofwork.Product.Remove(cat);
            _unitofwork.save();
            return Json(new
            {
                success = true,
                Message = "Finally DATA delete"
            });
        }

        
        }
    #endregion
}

Project/Areas/Adimen/Controllers/userController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Project_Data_Access.Data;
using Project_Data_Access.Repository;
using Project_Model;
using Project_utility;
using System.Data;

namespace Project.Areas.Adimen.Controllers
{
    [Area("Adimen")]
 // [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class userController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Iunitofwork _unitofwork;
        public userController(ApplicationDbContext context, Iunitofwork unitofwork)
        {
            _context = context;
            _unitofwork= unitofwork;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpPost]
        public IActionResult LockUnLock([FromBody] string id)
        {
            var lockout = _context.ApplicationUsers.Find(id);
            bool islocked=false;
            if(lockout==null)
                return Json(new {success=false, Message="somethink went worng locking"});
            if (lockout!=null && lockout.LockoutEnd > DateTime.Now   )//unlock
            {
                lockout.LockoutEnd = DateTime.Now;
                islocked = false;
            }
            else {
                lockout.LockoutEnd = DateTime.Now.AddYears(100);
                islocked = true;
            }
            _context.SaveChanges();
            return Json(new { message=islocked==true?"Locked":"UnLocked",success=lockout });
        }

        [HttpGet]
        public IActionResult getall()
        {
            var userList = _context.ApplicationUsers.ToList();
            //aspNetUseers
            var roles = _context.Roles.ToList();
            //aspNetRoles
            var userRoles = _context.UserRoles.ToList();
            //aspnetuserRoles
            foreach (var user in userList)
            {
                var roleId = userRoles.FirstOrDefault(r => r.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(r => r.Id == roleId).Name;
                if (user.CompanyId != null)
                {
                    user.Company = new Company()
                    {
                        Name = _unitofwork.Company.get(Convert.ToInt32(user.CompanyId)).Name
                    };
                }
                if (user.CompanyId == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }
            }
            var adminUser = userList.FirstOrDefault(u => u.Role == SD.Role_Admin);
            userList.Remove(adminUser);
            return Json(new { data = userList });
          
        }
        #endregion
    }

}
    

Project/Views/Shared/Edit.cshtml
<div class="row">
    <div class="col">
        <button class="btn btn-success">update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-danger">Back TO List</a>
    </div>
</div>

Project/Views/Shared/_Creat.cshtml
<div class="row">
    <div class="col-3 offset-6">
        <button type="submit" class="btn btn-danger form-control">Creat</button>
    </div>
   <div class="col-3">
       <a asp-action="Index" class="btn btn-danger form-control">Back TO List</a>
   </div>
</div>

Project/Views/Shared/_Layout.cshtml
@using Project_utility   
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.styles.css" asp-append-version="true" />
    @*CSS REF*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Adimen" asp-controller="Cata" asp-action="pageing">Index1</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="customer" asp-controller="Home" asp-action="dropdowen">dropdowen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Adimen" asp-controller="Country" asp-action="Index">dropdowen</a>
                        </li> *@
                        <li class="nav-item">
                           @*  <a class="nav-link text-dark" asp-area="Adimen" asp-controller="" asp-action="Index">city</a> *@

                        </li>
                      @if (User.IsInRole(SD.Role_Admin)) 
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white " data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    @*  <a class="dropdown-item" href="#">Action</a>*@

                                    <a class="dropdown-item" asp-area="Adimen" asp-controller="Cata" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Adimen" asp-controller="covertype" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Adimen" asp-controller="Product" asp-action="Index">Product</a>

                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee)) 
                        {
                           <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Company/User </a>
                                <div class="dropdown-menu">


                                    <a class="dropdown-item" asp-area="Adimen" asp-controller="Company" asp-action="Index">CompanyList</a> 
                                    <a class="dropdown-item" asp-area="Adimen" asp-controller="user" asp-action="Index">userList</a>
                                    <a class="dropdown-item" asp-area="customer" asp-controller="Home" asp-action="Allorder">orderList</a>


                                </div>
                            </li>
                        }
                        @if (httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_cartSessionCount) != null && httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_cartSessionCount) != 0)
                        {
                            var count = httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_cartSessionCount);
                            <li>
                                <a asp-controller="cart" asp-action="Index" class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(@count)
                                    </a>
                            </li>                        
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderSection("Navbar", required: false)
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Shopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*JS REF*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>